import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

import "./globals.css";
import Container from "./components/Container";

const Header = dynamic(() => import("./components/Header"), { ssr: false });
const Footer = dynamic(() => import("./components/Footer"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-[#12111b]  font-poppins `}>
        <main className='flex flex-grow flex-col justify-between min-h-screen h-screen'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
